"""Changed inventory_lots.location_id from Not Nullable, to Nullable

Revision ID: 7d252f442a81
Revises: 47d431ca4703
Create Date: 2026-07-22 14:40:47.907050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d252f442a81'
down_revision: Union[str, Sequence[str], None] = '47d431ca4703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory_lots") as batch_op:
        batch_op.alter_column(
            'location_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inventory_lots") as batch_op:
        batch_op.alter_column(
            'location_id',
            existing_type=sa.INTEGER(),
            nullable=False)
    # ### end Alembic commands ###
