"""column spelling correction: recipes.yeild_unit_it to recipes.yield_unit_id

Revision ID: a4b8b8ce861d
Revises: 7d252f442a81
Create Date: 2026-08-01 00:56:56.880510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b8b8ce861d'
down_revision: Union[str, Sequence[str], None] = '7d252f442a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes") as batch_op:
        batch_op.alter_column(
            "yeild_unit_id",
            new_column_name="yield_unit_id"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes") as batch_op:
        batch_op.alter_column(
            "yield_unit_id",
            new_column_name="yeild_unit_id"
        )
    # ### end Alembic commands ###
