"""Fixed Decimal precision and scale on quantities, moneies, and base unit costs. Also added CheckConstraint on vendor_items.usable_factor to keep it limited to 0-1.

Revision ID: a4c3015c9b0e
Revises: a4b8b8ce861d
Create Date: 2026-08-11 13:03:27.801357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c3015c9b0e'
down_revision: Union[str, Sequence[str], None] = 'a4b8b8ce861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "ingredient_unit_conversions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=20),
               existing_nullable=False)
    with op.batch_alter_table(
        "inventory_lots",
        schema=None
    ) as batch_op:
        batch_op.alter_column('original_qty',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('remaining_qty',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('base_unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=25, scale=20),
               existing_nullable=False)
    with op.batch_alter_table(
        "inventory_transactions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('qty_change',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    with op.batch_alter_table(
        "purchase_items",
        schema=None
    ) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('case_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('extended_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipe_components",
        schema=None
    ) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipe_productions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('quantity_produced',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipes",
        schema=None
    ) as batch_op:
        batch_op.alter_column('yield_qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('serving_qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    with op.batch_alter_table(
        "units",
        schema=None
    ) as batch_op:
        batch_op.alter_column('factor',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=25, scale=20),
               existing_nullable=False)
    with op.batch_alter_table(
        "vendor_item_conversions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    with op.batch_alter_table(
        "vendor_items",
        schema=None
    ) as batch_op:
        batch_op.alter_column('pack_size',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
        batch_op.alter_column('usable_factor',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=21, scale=20),
               existing_nullable=False)
        batch_op.alter_column('most_recent_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=10),
               existing_nullable=False)
        batch_op.create_check_constraint(
            "ck_vendor_items_usable_factor_range",
            "usable_factor > 0 AND usable_factor <= 1",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "vendor_items",
        schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            "ck_vendor_items_usable_factor_range",
            type_="check"
        )
        batch_op.alter_column('most_recent_price',
               existing_type=sa.Numeric(precision=15, scale=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usable_factor',
               existing_type=sa.Numeric(precision=21, scale=20),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('pack_size',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "vendor_item_conversions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    with op.batch_alter_table(
        "units",
        schema=None
    ) as batch_op:
        batch_op.alter_column('factor',
               existing_type=sa.Numeric(precision=25, scale=20),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipes",
        schema=None
    ) as batch_op:
        batch_op.alter_column('serving_qty',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('yield_qty',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipe_productions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('quantity_produced',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "recipe_components",
        schema=None
    ) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "purchase_items",
        schema=None
    ) as batch_op:
        batch_op.alter_column('extended_cost',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('case_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    with op.batch_alter_table(
        "inventory_transactions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('qty_change',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    with op.batch_alter_table(
        "inventory_lots",
        schema=None
    ) as batch_op:
        batch_op.alter_column('base_unit_cost',
               existing_type=sa.Numeric(precision=25, scale=20),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('remaining_qty',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('original_qty',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    with op.batch_alter_table(
        "ingredient_unit_conversions",
        schema=None
    ) as batch_op:
        batch_op.alter_column('multiplier',
               existing_type=sa.Numeric(precision=25, scale=20),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
